# node image
FROM node:9 as build

# create dir to host application
RUN mkdir -b /app

# Get the tarball and unzip to directory 
# format package/dist

WORKDIR /app

COPY . /app


# nginx image 
FROM nginx:1

COPY from-build /app/dist /usr/share/nginx/html

COPY ./app.conf /etc/nginx/conf.d/default.conf
